/*
 * Program.cs - Flame Badge
 *      -- Autogenerated mainfile for project.
 *      -- Only job is to call FlameBadge singleton.
 *      
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FlameBadge
{
    class Program
    {
        // initialize main game object
        static void Main(string[] args)
        {
            FlameBadge main = new FlameBadge();
        }
    }
}
